stages:
  data_ingestion:
    cmd: python3 src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python3 src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python3 src/features/feature_engineering.py
    deps:
    - data/processed
    - src/features/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/interim
  model_building:
    cmd: python3 src/model/model_building.py
    deps:
    - data/interim
    - src/model/model_building.py
    params:
    - model_building.n_estimators
    - model_building.learning_rate
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python3 src/model/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model/model_evaluation.py
    metrics:
    - metrics.json
